#!/bin/bash
#SBATCH -A r00279 
#SBATCH -J slimalignments                                  
#SBATCH -p general
#SBATCH -o slimalignments_%j.txt
#SBATCH -e slimalignments_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

# linkedp1
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedp1_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedp1_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 15

# linkedancestor
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_linkedancestor_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_linkedancestor_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 15

# balancing
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_balancing_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/nomig_neutral_scaled_20000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_balancing_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 15

# adaptiveint
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_adaptiveint_scaled_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/SLiM-testing-redo-revisions/p1_p2_neutral_scaled_20000/ -o bpp_alignments -p 15

