#!/bin/bash
#SBATCH -A r00279 
#SBATCH -J drosophilaalignments                                  
#SBATCH -p general
#SBATCH -o drosophilaalignments_%j.txt
#SBATCH -e drosophilaalignments_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

# linkedp1
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedp1_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedp1_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 15

# linkedancestor
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_linkedancestor_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_linkedancestor_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 15

# balancing
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_balancing_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/nomig_neutral_drosophila_20000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_balancing_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 15

# adaptiveint
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_1250/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_1250/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_5000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_5000/ -o bpp_alignments -p 15
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 5
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 10
python ./python_scripts/create_alignment_adaptive.py -s /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_adaptiveint_drosophila_20000/ -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/DROSOPHILA-testing-redo-revisions-v2/p1_p2_neutral_drosophila_20000/ -o bpp_alignments -p 15

