#!/bin/bash
#SBATCH -A general
#SBATCH -J DROSOPHILA_adaptiveint_20000                                   
#SBATCH -p general
#SBATCH -o DROSOPHILA_adaptiveint_20000_%j.txt
#SBATCH -e DROSOPHILA_adaptiveint_20000_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_20000/p1_p2_adaptiveint.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_20000_phy


 
