#!/bin/bash
#SBATCH -A general
#SBATCH -J SliM_bgs_5000                                   
#SBATCH -p general
#SBATCH -o SliM_bgs_5000_%j.txt
#SBATCH -e SliM_bgs_5000_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_5000/nomig_bgs.msOut -l 500 -n 10000 -o ./alignments/SLiM-testing-redo/nomig_bgs_5000_500bp_phy 
python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_5000/p1_p2_bgs.msOut -l 500 -n 10000 -o ./alignments/SLiM-testing-redo/p1_p2_bgs_5000_500bp_phy
python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_5000/p2_p1_bgs.msOut -l 500 -n 10000 -o ./alignments/SLiM-testing-redo/p2_p1_bgs_5000_500bp_phy


 
