#!/bin/bash
#SBATCH -A general
#SBATCH -J DROSOPHILA_linkedp1_20000                                   
#SBATCH -p general
#SBATCH -o DROSOPHILA_linkedp1_20000_%j.txt
#SBATCH -e DROSOPHILA_linkedp1_20000_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_20000/nomig_linkedp1.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_20000_phy 
python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_20000/p1_p2_linkedp1.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_20000_phy
python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_20000/p2_p1_linkedp1.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_20000_phy


 
