#!/bin/bash
#SBATCH -A general
#SBATCH -J DROSOPHILA_linkedancestor_1250                                   
#SBATCH -p general
#SBATCH -o DROSOPHILA_linkedancestor_1250_%j.txt
#SBATCH -e DROSOPHILA_linkedancestor_1250_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_1250/nomig_linkedancestor.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_1250_phy 
python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_1250/p1_p2_linkedancestor.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_1250_phy
python ./python_scripts/msout_to_phylip.py -m ../DROSOPHILA-testing-redo/testingSims_1250/p2_p1_linkedancestor.msOut -l 500 -n 1500 -o ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_1250_phy


 
