#!/bin/bash
#SBATCH -A general
#SBATCH -J SLiM_bgs_1250                                
#SBATCH -p general
#SBATCH -o SLiM_bgs_1250_%j.txt
#SBATCH -e SLiM_bgs_1250_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_1250/nomig_bgs.msOut -l 500 -n 10000 -o ./alignments/SLiM-testing-redo/nomig_bgs_1250_500bp_phy 
python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_1250/p1_p2_bgs.msOut -l 500 -n 10000 -o ./alignments/SLiM-testing-redo/p1_p2_bgs_1250_500bp_phy
python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_1250/p2_p1_bgs.msOut -l 500 -n 10000 -o ./alignments/SLiM-testing-redo/p2_p1_bgs_1250_500bp_phy


 
