#!/bin/bash
#SBATCH -A general
#SBATCH -J SLiM_linkedp1_5000                                   
#SBATCH -p general
#SBATCH -o SLiM_linkedp1_5000_%j.txt
#SBATCH -e SLiM_linkedp1_5000_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_5000/nomig_linkedp1.msOut -l 500 -n 1500 -o ./alignments/SLiM-testing-redo/nomig_linkedp1_5000_phy 
python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_5000/p1_p2_linkedp1.msOut -l 500 -n 1500 -o ./alignments/SLiM-testing-redo/p1_p2_linkedp1_5000_phy
python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_5000/p2_p1_linkedp1.msOut -l 500 -n 1500 -o ./alignments/SLiM-testing-redo/p2_p1_linkedp1_5000_phy


 
