#!/bin/bash
#SBATCH -A general
#SBATCH -J SLiM_adaptiveint_20000                                   
#SBATCH -p general
#SBATCH -o SLiM_adaptiveint_20000_%j.txt
#SBATCH -e SLiM_adaptiveint_20000_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=10:00:00

module load python

python ./python_scripts/msout_to_phylip.py -m ../SLiM-testing-redo/testingSims_20000/p1_p2_adaptiveint.msOut -l 500 -n 1500 -o ./alignments/SLiM-testing-redo/p1_p2_adaptiveint_20000_phy


 
