# BGS
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_bgs_scaled_1250
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_bgs_scaled_5000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_bgs_scaled_20000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_bgs_scaled_1250
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_bgs_scaled_5000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_bgs_scaled_20000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_bgs_scaled_1250
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_bgs_scaled_5000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_bgs_scaled_20000
  
# Neutral
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/nomig_neutral_1250_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_neutral_scaled_1250
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/nomig_neutral_5000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_neutral_scaled_5000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/nomig_neutral_20000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_neutral_scaled_20000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p1_p2_neutral_1250_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_neutral_scaled_1250
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p1_p2_neutral_5000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_neutral_scaled_5000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p1_p2_neutral_20000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_neutral_scaled_20000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p2_p1_neutral_1250_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_neutral_scaled_1250
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p2_p1_neutral_5000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_neutral_scaled_5000
python python_scripts/run_bpp_v1a.py -a ./alignments/DROSOPHILA-testing-redo/p2_p1_neutral_20000_500bp_phy/ -o ./bpp_input/DROSOPHILA-testing-redo/ -p ./bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_neutral_scaled_20000
 
  
# Linked P1: nomig
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedp1_20000_15percent --percent 15
  
# Linked P1: p1_p2
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedp1_20000_15percent --percent 15
  
# Linked P1: p2_p1
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedp1_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedp1_20000_15percent --percent 15
  
# Linked Ancestor: nomig
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/nomig_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/nomig_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix nomig_linkedancestor_20000_15percent --percent 15
  
# Linked Ancestor: p1_p2
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_linkedancestor_20000_15percent --percent 15
  
# Linked Ancestor: p2_p1
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p2_p1_linkedancestor_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p2_p1_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p2_p1_linkedancestor_20000_15percent --percent 15

# Adaptive Introgression: p1_p2 
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_1250_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_1250_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_5000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_5000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_v1a.py  -a ./alignments/DROSOPHILA-testing-redo/p1_p2_adaptiveint_20000_phy/ -b ./alignments/DROSOPHILA-testing-redo/p1_p2_bgs_20000_500bp_phy/ -o bpp_input/DROSOPHILA-testing-redo/ -p bpp_output/DROSOPHILA-testing-redo/ --prefix p1_p2_adaptiveint_20000_15percent --percent 15