# neutral
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_neutral_scaled_1250
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_neutral_scaled_5000
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_neutral_scaled_20000

python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_neutral_scaled_1250
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_neutral_scaled_5000
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_neutral_scaled_20000

python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_neutral_scaled_1250
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_neutral_scaled_5000
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_neutral_scaled_20000

# BGS
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_bgs_scaled_1250
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_bgs_scaled_5000
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_bgs_scaled_20000

python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_bgs_scaled_1250
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_bgs_scaled_5000
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_bgs_scaled_20000

python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_bgs_scaled_1250
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_bgs_scaled_5000
python python_scripts/run_bpp_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o ./bpp_input_heredity_longer/SLiM-testing-redo/ -p ./bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_bgs_scaled_20000

# linked p1
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedp1_20000_15percent --percent 15

python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedp1_20000_15percent --percent 15

python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedp1_20000_15percent --percent 15

# linked ancestor
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix nomig_linkedancestor_20000_15percent --percent 15

python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_linkedancestor_20000_15percent --percent 15

python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p2_p1_linkedancestor_20000_15percent --percent 15

# adaptiveint
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_1250_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_1250_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_1250_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_5000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_5000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_5000_15percent --percent 15
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_20000_5percent --percent 5
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_20000_10percent --percent 10
python python_scripts/run_bpp_adaptive_heredity_longer_v1a.py -a ./bpp_input/SLiM-testing-redo/ -o bpp_input_heredity_longer/SLiM-testing-redo/ -p bpp_output_heredity_longer/SLiM-testing-redo/ --prefix p1_p2_adaptiveint_20000_15percent --percent 15
