# nomig
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_bgs_drosophila_20000_1.ctl -o nomig_bgs_drosophila_20000_1 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_bgs_drosophila_20000_2.ctl -o nomig_bgs_drosophila_20000_2 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_bgs_drosophila_20000_3.ctl -o nomig_bgs_drosophila_20000_3 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_bgs_drosophila_20000_4.ctl -o nomig_bgs_drosophila_20000_4 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_bgs_drosophila_20000_5.ctl -o nomig_bgs_drosophila_20000_5 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force

# p1_p2
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/p1_p2_bgs_drosophila_20000_1.ctl -o p1_p2_bgs_drosophila_20000_1 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/p1_p2_bgs_drosophila_20000_2.ctl -o p1_p2_bgs_drosophila_20000_2 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/p1_p2_bgs_drosophila_20000_3.ctl -o p1_p2_bgs_drosophila_20000_3 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/p1_p2_bgs_drosophila_20000_4.ctl -o p1_p2_bgs_drosophila_20000_4 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/p1_p2_bgs_drosophila_20000_5.ctl -o p1_p2_bgs_drosophila_20000_5 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force

# neutral
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_neutral_drosophila_20000_1.ctl -o nomig_neutral_drosophila_20000_1 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_neutral_drosophila_20000_2.ctl -o nomig_neutral_drosophila_20000_2 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_neutral_drosophila_20000_3.ctl -o nomig_neutral_drosophila_20000_3 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_neutral_drosophila_20000_4.ctl -o nomig_neutral_drosophila_20000_4 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force
python python_scripts/submit_bayes_factor.py -c /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/bpp_ctl/nomig_neutral_drosophila_20000_5.ctl -o nomig_neutral_drosophila_20000_5 -b /N/project/Prophysaongenomics/FILET_Organized_24January2023/bpp-redo-revision/ --force

